version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend
            - run: docker run -d -p 6379:6379 --name redis1 redis
            - run: npm install
            - run: npm test
            - run: docker stop redis1
            - run: docker rm redis1
workflows:
    build-and-test:
      jobs:
        - build-and-test